sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t testimage -f Dockerfile.dev .

script:
  - docker run -e CI=true testimage npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "dockerlearn"
  env: "Dockerlearn-env"
  bucket_name: "elasticbeanstalk-eu-north-1-094664373066"
  bucket_path: "dockerlearn"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
